name: Commit Message Check
on: push

jobs:
 test:
   runs-on: [ ubuntu-latest ]
   steps:
     - name: Commit Message Check
       if: contains(github.event.head_commit.message, '():')
       run: |
         echo 'Verifying Commit Message ${github.event.head_commit.message}!'