name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  verify-commit-message:
    if: "contains(github.event.head_commit.message, '():')"
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        run: true
  reject-commit-message:
    if: "!contains(github.event.head_commit.message, '():')"
    name: Reject Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Type
        run: exit 1
#test
