# This is a basic workflow to help you get started with Actions

name: use POC workflow

# Controls when the workflow will run
on:
  repository_dispatch:
  push:
    branches:
        #push on main not allowed cus its protected
      - 'release/**'
      - 'feature/**'
      - 'dev/**'
      - 'hotfix/**'
      - 'bug/**'
        #push on branch with prefix "release/", "feature/" etc.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Set output
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Check output
        run: echo ${{ steps.vars.outputs.short_ref }}

  use_workflow:
    uses: TOwens1987/SUPERAwesomeProject/.github/workflows/gitversionOnMain.yml@main
#test