name: Search Release Description
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'The owner and name of the repository to search in (e.g., owner/repo).'
        required: true
      release:
        description: 'The ID or tag of the release to search in.'
        required: true
jobs:
  search:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Search release description
        run: |
          RELEASE_BODY=$(curl -s https://api.github.com/repos/${{ github.event.inputs.repo }}/releases/${{ github.event.inputs.release }} | jq -r '.body')
          echo "${RELEASE_BODY}" | grep -E -i "Description\s+([^<]+)" -o | sed 's/Description\s*//g'