name: Search Release Description
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'The owner and name of the repository to search in (e.g., owner/repo).'
        required: true
      release:
        description: 'The ID or tag of the release to search in.'
        required: true
jobs:
  search_release_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Search release notes
        id: search
        run: |
          description=$(curl -s https://api.github.com/repos/<OWNER>/<REPO>/releases/tags/<TAG> | jq -r '.body' | grep -i description)
          echo "::set-output name=description::$description"

      - name: Display results
        run: |
          echo "${{ steps.search.outputs.description }}"| grep -E -i "Description\s+([^>]+)" -o | sed 's/Description\s*//g'