# This is a basic workflow to help you get started with Actions

name: Remote Versioning workflow

# Controls when the workflow will run
on:
  repository_dispatch:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  use_workflow:
    uses: Towens1987/GitVersioning/.github/workflows/Versioning.yml@main