name: Create New Tag

on:
  workflow_call:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.adoc"
      - "docs/*"
      - ".github/**"
      - ".git*"

jobs:
  Tagging:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: minor-release
        id: tag_version1
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
          create_annotated_tag: true
          tag_prefix: ""

      - name: Create a GitHub release for minor bump
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version1.outputs.new_tag }}
          name: Release ${{ steps.tag_version1.outputs.new_tag }}
          body: ${{ github.event.pull_request.body }}
